version: 2
docker:
  image: circeci/node:8

steps:
  - checkout
  - run: curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - run: sudo dpkg -i google-chrome.deb
  - run: sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
  - run: rm google-chrome.deb